
n_cpu: '1'
NTH_PDB2XYZ: 1
NTH_GUESS: 1
NTH_GENETIC: 1

atoms:
  - 'CA'

seed: 123
thr: 12
pdb_ext: 'ent'
n_population: 2048
max_iter: 16400
precision: '1e-4'
elit: .1
mutation: .3
folders:
  pdb_dir: 'proteinPDB'
  protein_dir: 'proteinXYZ'
  guessed_dir: 'proteinGUESS'
  rec_dir: 'proteinREC'
  cpp: 'cpp'
  py: 'python'

