
n_cpu: '1'
NTH_PDB2XYZ: 1
NTH_GUESS: 1
NTH_GENETIC: 1

atoms:
  - 'CA'

seed: 123
thr: 8
pdb_ext: 'pdb'
n_population: 2048
max_iter: 16400
precision: '1e-4'
elit: .1
mutation: .3
folders:
  pdb_dir: 'protein'
  cpp: 'cpp'
  py: 'py'

#curl "http://files.rcsb.org/view/{1PPE,1AVW,1BRC}.pdb" -o "#1.pdb"
protein:
  - 1PPE
  - 1AVW
  - 1BRC
  - 4D2I
  - 4CS4
